# Generated by Django 2.1 on 2018-09-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=40)),
                ('quantidade', models.IntegerField()),
                ('preco', models.FloatField()),
            ],
        ),
    ]
